### ISSUE TITLE
Update package on pypi.

### ISSUE THREAD

**Issue by beppler** [asterisk/starpy#18]
The starpy package on pypi.python.org points to version 1.0.0a11 and to the sourceforge (very old version).

Can you upload the new versions or there are no contact with the owner of the package on pypi?

**Comment by creslin287** [comment]
Hey,

Sorry, this is a copy/paste message for both pull requests and open issues on github against the starpy project - apply it appropriately.

Just as a heads up, we have moved starpy over to gerrit.asterisk.org so that the code contribution process works similarly to other codebases maintained by the Asterisk project.  You can find more information about how to contribute code in that environment at https://wiki.asterisk.org/wiki/display/AST/Gerrit+Usage

As part of this change, we’re going to be closing any github based pull requests against starpy.  It is advisable to re-submit them as code reviews on gerrit.asterisk.org against the starpy project.

Similarly, we are moving issue tracking for the starpy project over to issues.asterisk.org.  As part of this change, we are going to close any outstanding issues against starpy on github.  Feel free to migrate any issues that remain relevant to issues.asterisk.org under the starpy project.

For any questions or comments about this, feel free to email us on the asterisk-dev mailing list at lists.digium.com or see a developer on irc.freenode.net in the #asterisk-dev IRC channel.

Thanks, and sorry again about the inconvenience.

Sincerely,
The Asterisk Development Team
