### ISSUE TITLE
Connection randomly closes itself

### ISSUE THREAD

**Issue by klismannsm** [asterisk/starpy#22]
Hi,

I have an application which uses the newest version of starpy and works well for most of the time on most machines it is being used, but randomly stops on some of them.

What happens: The factory stops itself (  Stopping factory <starpy.manager.AMIFactory instance at 0x1dd6998> ) and an error is thrown.
The error given is: " sequence index must be integer, not 'str' ", which doens't seem to be anything with my code.
Sometimes this error is preceded by the following error:

File "/usr/lib64/python2.6/logging/**init**.py", line 797, in emit
[AMIProtocol,client]     stream.write(fs % msg)
[AMIProtocol,client] IOError: [Errno 5] Input/output error

The code randomly throws an error in one of the two following partial codes:
Notes: I'm using the " @defer.inlineCallbacks " decorator and the variable client contains the connection.

try:
    dndExtensions = []
    dnd = yield client.command ( 'database show DND' )
    for extension in dnd:
        if 'DND' in extension:
            dndExtensions.append ( extension.split ( '/DND/' )[1].split (' ')[0] )
except Exception, e:
    # error ...

try:
    lunchExtensions = []
    lunch = yield client.command ( 'database show Lunch' )
    for extension in lunch:
        if 'Lunch' in extension:
            lunchExtensions.append ( extension.split ( '/Lunch/' )[1].split (' ')[0] )
except Exception, e:
    # error ...

Any idea of what might be happening?

**Comment by creslin287** [comment]
Hey,

Sorry, this is a copy/paste message for both pull requests and open issues on github against the starpy project - apply it appropriately.

Just as a heads up, we have moved starpy over to gerrit.asterisk.org so that the code contribution process works similarly to other codebases maintained by the Asterisk project.  You can find more information about how to contribute code in that environment at https://wiki.asterisk.org/wiki/display/AST/Gerrit+Usage

As part of this change, we’re going to be closing any github based pull requests against starpy.  It is advisable to re-submit them as code reviews on gerrit.asterisk.org against the starpy project.

Similarly, we are moving issue tracking for the starpy project over to issues.asterisk.org.  As part of this change, we are going to close any outstanding issues against starpy on github.  Feel free to migrate any issues that remain relevant to issues.asterisk.org under the starpy project.

For any questions or comments about this, feel free to email us on the asterisk-dev mailing list at lists.digium.com or see a developer on irc.freenode.net in the #asterisk-dev IRC channel.

Thanks, and sorry again about the inconvenience.

Sincerely,
The Asterisk Development Team
